version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
